// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/bookings.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/sunil-dev608/space-trouble/internal/pkg/model"
)

// MockBookingRepository is a mock of BookingRepository interface.
type MockBookingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookingRepositoryMockRecorder
}

// MockBookingRepositoryMockRecorder is the mock recorder for MockBookingRepository.
type MockBookingRepositoryMockRecorder struct {
	mock *MockBookingRepository
}

// NewMockBookingRepository creates a new mock instance.
func NewMockBookingRepository(ctrl *gomock.Controller) *MockBookingRepository {
	mock := &MockBookingRepository{ctrl: ctrl}
	mock.recorder = &MockBookingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingRepository) EXPECT() *MockBookingRepositoryMockRecorder {
	return m.recorder
}

// CreateBooking mocks base method.
func (m *MockBookingRepository) CreateBooking(ctx context.Context, booking *model.BookingDB) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBooking", ctx, booking)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBooking indicates an expected call of CreateBooking.
func (mr *MockBookingRepositoryMockRecorder) CreateBooking(ctx, booking interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooking", reflect.TypeOf((*MockBookingRepository)(nil).CreateBooking), ctx, booking)
}

// DeleteBooking mocks base method.
func (m *MockBookingRepository) DeleteBooking(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBooking", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBooking indicates an expected call of DeleteBooking.
func (mr *MockBookingRepositoryMockRecorder) DeleteBooking(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBooking", reflect.TypeOf((*MockBookingRepository)(nil).DeleteBooking), ctx, id)
}

// GetAllBookings mocks base method.
func (m *MockBookingRepository) GetAllBookings(ctx context.Context) ([]model.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBookings", ctx)
	ret0, _ := ret[0].([]model.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBookings indicates an expected call of GetAllBookings.
func (mr *MockBookingRepositoryMockRecorder) GetAllBookings(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBookings", reflect.TypeOf((*MockBookingRepository)(nil).GetAllBookings), ctx)
}

// HasConflictingFlight mocks base method.
func (m *MockBookingRepository) HasConflictingFlight(ctx context.Context, booking *model.BookingDB) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasConflictingFlight", ctx, booking)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasConflictingFlight indicates an expected call of HasConflictingFlight.
func (mr *MockBookingRepositoryMockRecorder) HasConflictingFlight(ctx, booking interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasConflictingFlight", reflect.TypeOf((*MockBookingRepository)(nil).HasConflictingFlight), ctx, booking)
}
