CREATE TABLE IF NOT EXISTS BOOKINGS (
    ID              SERIAL PRIMARY KEY,
    FIRST_NAME      TEXT NOT NULL,
    LAST_NAME       TEXT NOT NULL,
    GENDER          TEXT NOT NULL,
    BIRTHDAY        DATE NOT NULL,
    DESTINATION_ID  TEXT NOT NULL,
    LAUNCHPAD_ID    TEXT NOT NULL,
    LAUNCH_DATE     DATE NOT NULL
);

CREATE INDEX IF NOT EXISTS DESTINATION_IDX ON BOOKINGS (DESTINATION_ID);
CREATE INDEX IF NOT EXISTS LAUNCHPAD_IDX ON BOOKINGS (LAUNCHPAD_ID);
CREATE INDEX IF NOT EXISTS LAUNCH_DATE_IDX ON BOOKINGS (LAUNCH_DATE);
