CREATE TABLE BOOKINGS (
    ID              SERIAL PRIMARY KEY,
    FIRST_NAME      TEXT NOT NULL,
    LAST_NAME       TEXT NOT NULL,
    GENDER          TEXT NOT NULL,
    BIRTHDAY        DATE NOT NULL,
    DESTINATION_ID  TEXT NOT NULL,
    LAUNCHPAD_ID    TEXT NOT NULL,
    LAUNCH_DATE     DATE NOT NULL
);
